name: oggm_edu_docs
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - shapely
  - requests
  - configobj
  - netcdf4
  - xarray
  - pytables
  - pytest
  - seaborn
  - sphinx
  - sphinx-book-theme>=0.3.2
  - ipython
  - numpydoc
  - sphinx-intl
  - pip:
    - git+https://github.com/OGGM/oggm
    - git+https://github.com/OGGM/oggm-edu
    # relative to this file. Needs to be editable to be accepted.
    - -e ..
